version: '3'

services:
  django:
    # build указывает путь к dockerfile по которому будем собирать текущий сервис
    build: .
    container_name: my_django_project
    # command указывает команды которые будут выполняться при сборке текущего сервиса django
    # запускаем локальный встроенный сервер django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      # порт локальной машины : порт внутри контейнеров
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      # бемер весь локальный проект : прекидываем внутрь контейнера
      # путь к контейнеру берем из WORKDIR (dockerfile)
      . : /usr/src/app

  
  postgres_db:
    image: postgres:latest
    # хранит переменные которые нужны будут для подключения к текущей базе данных
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: my_postgres_db